export const adjectives = [
    "Amazing", "Adept", "Ambivalent", "Angry",
    "Boastful", "Big", "Bold", "Belligerent",
    "Capable", "Crafty", "Cozy", "Calm",
    "Direct", "Dynamic", "Dizzy", "Daring",
    "Eager", "Elegant", "Expert", "Extreme",
    "Funny", "Friendly", "Furious", "Frozen",
    "Grand", "Generous", "Grim", "Gentle",
    "Hopeful", "Heroic", "Hidden", "Howling",
    "Indoor", "Imperious", "Ideal", "Illustrious",
    "Jovial", "Joking", "Just", "Jolly",
    "Kind", "Knowledgeable",
    "Lucky", "Likable", "Luminous", "Lazy",
    "Mysterious", "Modest", "Mindful", "Miniature",
    "Nimble", "Noisy", "Nervous", "Nuanced",
    "Old", "Optimal", "Observant",
    "Passionate", "Patient", "Peaceful", "Playful",
    "Quaint", "Quick", "Quiet",
    "Radiant", "Remarkable", "Rowdy", "Royal",
    "Shiny", "Strong", "Shy", "Short",
    "Tough", "Tall", "Thriving", "Tranquil",
    "Ultimate", "Upbeat", "Undaunted",
    "Versatile", "Vibrant", "Valiant", "Victorious",
    "Warm", "Wise", "Witty", "Whimsical",
    "Yawning",
    "Zany", "Zealous",
];

export const animals = [
    "Aardvark", "Alligator", "Alpaca", "Anaconda", "Ant", "Anteater", "Antelope", "Aphid", "Armadillo", "Asp",
    "Baboon", "Badger", "Barracuda", "Bass", "Bat", "Bear", "Beaver", "Bee", "Bird", "Bison", "Bobcat", "Buffalo", "Butterfly", "Beetle",
    "Camel", "Carp", "Cat", "Caterpillar", "Catfish", "Cheetah", "Chicken", "Chipmunk", "Cobra", "Condor", "Cougar", "Cow", "Coyote", "Crab", "Cricket", "Crocodile", "Crow",
    "Deer", "Dog", "Dolphin", "Donkey", "Dove", "Dragonfly", "Duck",
    "Eagle", "Eel", "Elephant", "Emu",
    "Falcon", "Ferret", "Finch", "Fish", "Flamingo", "Flea", "Fly", "Fox", "Frog",
    "Goat", "Goose", "Gopher", "Guinea Pig",
    "Hamster", "Hare", "Hawk", "Hippopotamus", "Horse", "Hummingbird",
    "Iguana", "Impala",
    "Jackal",
    "Kangaroo", "Koala",
    "Lemur", "Leopard", "Lion", "Lizard", "Llama", "Lobster",
    "Moose", "Mosquito", "Moth", "Mouse", "Mule", "Mole",
    "Newt",
    "Octopus", "Orca", "Ostrich", "Otter", "Owl", "Ox", "Oyster",
    "Panda", "Parrot", "Peacock", "Pelican", "Penguin", "Pheasant", "Pig", "Pigeon", "Porcupine",
    "Quail", "Quokka",
    "Rabbit", "Raccoon", "Rat", "Rooster", "Rhino",
    "Salmon", "Seal", "Sheep", "Skunk", "Sloth", "Snail", "Snake", "Spider",
    "Tiger",
    "Vulture",
    "Whale", "Wolf", "Wombat",
    "Yak",
    "Zebra",
];
